# Generated by Django 6.0.5 on 2026-05-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('routine_type', models.CharField(choices=[('hipertrofia', 'Pesas (Hipertrofia)'), ('mma', 'Clases de MMA'), ('descanso', 'Día de Descanso')], max_length=20, verbose_name='Tipo de Rutina')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Día')),
            ],
        ),
        migrations.CreateModel(
            name='Supplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_grams', models.PositiveIntegerField(default=0, verbose_name='Proteína (g)')),
                ('creatine_grams', models.PositiveIntegerField(default=0, verbose_name='Creatina (g)')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='tracker.trainingday')),
            ],
        ),
    ]
